### ISSUE TITLE
org.powermock.reflect.exceptions.FieldNotFoundException: Field 'fTestClass' was not found in class org.junit.internal.runners.MethodValidator.

### ISSUE THREAD

**Issue by snowdream** [snowdream/SnowdreamFramework#28]
when use unit test lib as follows.
```
    testCompile 'junit:junit:4.12'
    // required if you want to use Mockito for unit tests
    testCompile 'org.mockito:mockito-core:1.9.5'
    // required if you want to use Powermock for unit tests
    testCompile 'org.powermock:powermock-module-junit4:1.5.6'
    testCompile 'org.powermock:powermock-api-mockito:1.5.6'
```

error occurs:
```
/usr/lib/jvm/java-8-oracle/bin/java -ea -Didea.launcher.port=7537 -Didea.launcher.bin.path=/home/snowdream/bin/idea-IU-162.1121.32/bin -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath /home/snowdream/bin/idea-IU-162.1121.32/lib/idea_rt.jar:/home/snowdream/bin/idea-IU-162.1121.32/plugins/junit/lib/junit-rt.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/home/snowdream/bin/android-sdk-linux/platforms/android-23/android.jar:/home/snowdream/bin/android-sdk-linux/platforms/android-23/data/res:/home/snowdream/snowdream/git/SnowdreamFramework/modules/core/build/intermediates/classes/test/debug:/home/snowdream/snowdream/git/SnowdreamFramework/modules/core/build/intermediates/classes/debug:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/jars/classes.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/res:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/jars/libs/internal_impl-24.1.1.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/com.google.dexmaker/dexmaker/1.2/4d5045fefa6d286c5ddf733e321fe6e5e632efb6/dexmaker-1.2.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-exec/1.3/8dfb9facd0830a27b1b5f29f84593f0aeee7773b/commons-exec-1.3.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-module-junit4-common/1.5.6/3cc7cf1df7a7283b6b1c96a52a8ea4d183deea31/powermock-module-junit4-common-1.5.6.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-library/1.3/4785a3c21320980282f9f33d0d1264a69040538f/hamcrest-library-1.3.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/core/libs/annotations.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.getkeepsafe.relinker/relinker/1.2.1/jars/classes.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.getkeepsafe.relinker/relinker/1.2.1/res:/home/snowdream/.gradle/caches/modules-2/files-2.1/com.google.dexmaker/dexmaker-mockito/1.2/b99884a4c6ef6335ba376f79aa79632b2421c17c/dexmaker-mockito-1.2.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.1/905075e6c80f206bbe6cf1e809d2caa69f420c76/commons-lang3-3.1.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/com.jayway.awaitility/awaitility/1.7.0/e4fa7955cab67d880e4868a0795cce3498ea7bf2/awaitility-1.7.0.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-reflect/1.5.6/962751c056e0d56edf1d419985e6d8032328555b/powermock-reflect-1.5.6.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.labo.kaji/fragmentanimations/0.1.0/jars/classes.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.labo.kaji/fragmentanimations/0.1.0/res:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-api-support/1.5.6/8884532ded864f892b03a0769fd212d34653d5f3/powermock-api-support-1.5.6.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/1.9.5/c3264abeea62c4d2f367e21484fbb40c7e256393/mockito-core-1.9.5.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/2.1/87c0ea803b69252868d09308b4618f766f135a96/objenesis-2.1.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.desarrollodroide/fragmenttransactionextended/1/res:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.desarrollodroide/fragmenttransactionextended/1/jars/classes.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/cglib/cglib-nodep/3.1/aa83efbd1aedc4f26bdf00e7ea78191483f2c9b3/cglib-nodep-3.1.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-all/1.9.5/79a8984096fc6591c1e3690e07d41be506356fa5/mockito-all-1.9.5.jar:/home/snowdream/bin/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/24.1.1/support-annotations-24.1.1.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/res:/home/snowdream/snowdream/git/SnowdreamFramework/modules/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/jars/classes.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/res:/home/snowdream/snowdream/git/SnowdreamFramework/modules/app/build/intermediates/exploded-aar/com.android.support/multidex/1.0.1/jars/classes.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-api-mockito/1.5.6/97f1e2bfbedc1a0459c4eacfe3524e367d1918d0/powermock-api-mockito-1.5.6.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.18.2-GA/1180a90fbad732b60fb728a6bbe8fcb3151423d7/javassist-3.18.2-GA.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-module-junit4/1.5.6/878ef25550c9e757d6073b70f3ab18c04f3bc33f/powermock-module-junit4-1.5.6.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.kogitune/pre-lollipop-activity-transition/1.3.0/jars/classes.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/main/build/intermediates/exploded-aar/com.kogitune/pre-lollipop-activity-transition/1.3.0/res:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-core/1.5.6/2cf9445b015ff4831487b6cb7667068b3a306066/powermock-core-1.5.6.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/util/build/intermediates/classes/debug:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/1.0/9b473564e792c2bdf1449da1f0b1b5bff9805704/objenesis-1.0.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/app/build/intermediates/exploded-aar/com.android.support/support-v4/21.0.3/res:/home/snowdream/snowdream/git/SnowdreamFramework/modules/app/build/intermediates/exploded-aar/com.android.support/support-v4/21.0.3/jars/classes.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/app/build/intermediates/exploded-aar/com.android.support/support-v4/21.0.3/jars/libs/internal_impl-21.0.3.jar:/home/snowdream/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.1/860340562250678d1a344907ac75754e259cdb14/hamcrest-core-1.1.jar:/home/snowdream/bin/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.jar:/home/snowdream/snowdream/git/SnowdreamFramework/modules/log/build/intermediates/classes/test/debug:/home/snowdream/snowdream/git/SnowdreamFramework/modules/log/build/intermediates/classes/debug com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.github.snowdream.android.widget.ToastTest,testCreateOrUpdateToastFromToastBean

org.powermock.reflect.exceptions.FieldNotFoundException: Field 'fTestClass' was not found in class org.junit.internal.runners.MethodValidator.

	at org.powermock.reflect.internal.WhiteboxImpl.getInternalState(WhiteboxImpl.java:581)
	at org.powermock.reflect.Whitebox.getInternalState(Whitebox.java:308)
	at org.powermock.modules.junit4.internal.impl.testcaseworkaround.PowerMockJUnit4MethodValidator.validateTestMethods(PowerMockJUnit4MethodValidator.java:79)
	at org.powermock.modules.junit4.internal.impl.testcaseworkaround.PowerMockJUnit4MethodValidator.validateInstanceMethods(PowerMockJUnit4MethodValidator.java:49)
	at org.junit.internal.runners.MethodValidator.validateMethodsForDefaultRunner(MethodValidator.java:51)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.validate(PowerMockJUnit44RunnerDelegateImpl.java:108)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.<init>(PowerMockJUnit44RunnerDelegateImpl.java:70)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl.<init>(PowerMockJUnit47RunnerDelegateImpl.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.<init>(PowerMockJUnit49RunnerDelegateImpl.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:149)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:39)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:218)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:59)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:96)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


Process finished with exit code 255

```

**Comment by snowdream** [comment]
http://stackoverflow.com/questions/26192929/unable-to-run-junit-test-with-powermockrunner

**Comment by snowdream** [comment]
https://github.com/spring-io/platform/issues/113
